version: '3.7'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: 'kensobi-histogram-panel'
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/kensobi-histogram-panel
      - ./provisioning:/etc/grafana/provisioning
    environment:
      - TERM=linux
      - GF_LOG_LEVEL=debug
      - GF_DATAPROXY_LOGGING=true
      - GF_DEFAULT_APP_MODE=development

